name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libsrt
      run: sudo apt-get update && sudo apt-get install -y libsrt-dev
    - name: make
      run: make
