name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libsrt
      run: sudo dnf install srt-devel -y
    - name: make
      run: make
